### ISSUE TITLE
Form submission in a plugin view

### ISSUE THREAD

**Issue by mitar** [divio/django-cms#2209]
Many plugins display some form to the user instead of static content. There is currently no supported way to process those forms except for redirecting the form to some stand-alone view, but this does not provide a good user experience if the form contains errors. In that case form should not submit to the stand-alone view but should show errors in the original page, along the form, so that user can fix it.

There was an early relevant ticket #79 closed by BDFL as no, but I urge to reconsider. Because it is not just a question of supporting redirect, but also whole form workflow. For example, what it there are multiple forms of the same plugin on a page.

Current options are:
* using Ajax to verify and submit the form
* submitting to the separate view, but this has issues with errors ([cmsplugin-poll](https://bitbucket.org/tonioo/cmsplugin-poll/src/56f3d155508c7bc00114c368c71d36eecdbaeb79/cmsplugin_poll/views.py?at=default) uses separate views and then display errors with messages)
* using [such middleware](http://djangosnippets.org/snippets/2541/), but the issue is that it requires admins to install one middleware more
* use iframe, but then it is a problem that you have to negotiate size of the iframe vs. internal and external content

Could maybe django CMS then provide such middleware? I believe whole community would benefit if there would be a common pattern here and not that we all have to discover solutions to this ourselves. I understand that CMS plugins were maybe meant only to render static content, but web is evolving and providing dynamic functions in plugins end-users can use is something common.

Relevant ticket in cmsplugin-contact: https://github.com/maccesch/cmsplugin-contact/issues/29

**Comment by FinalAngel** [comment]
@mkoistinen @yakky any update here? should we update this on our side?

**Comment by frnhr** [comment]
@ojii Please correct me if I'm wrong, but apphooks hijack the entire page. What if (or when) we want to show a form within a plugin, but still have CMS content, i.e. other plugins on the page?

**Comment by mkoistinen** [comment]
@frnhr I regularly use Placeholders and PlaceholderFields in apphook'ed content. This provides a seamless CMS content management experience into the apphooks.

Forms are quite problematic in a plugin as was pointed out above. CMSPlugins are generally for content fragments, not whole pages. From a REST point of view, plugins are just not the appropriate place for *standalone* form handling, since plugins don't have a canonical URL, the view/page does.

If you still need to process form submissions in the plugin and if AJAX-based form handling (see [AJAX-ified CMS Plugins](https://www.youtube.com/watch?v=XIdClQgYdzw)) isn't an option, consider making a ViewMixin for your app's View that collects and passes form posts into the context and let the plugins pick it up from there (see [Context Aware Plugins](https://www.youtube.com/watch?v=FItJ4dW_PPI)). Its not very efficient, makes things complicated and probably presents security concerns, but it is doable. No changes to the CMS required.

If you have a View, why not just process the form there and if you really need the ability to move things around on the resulting page, use a Placeholder(Field) in your template and put your form in a plugin. No problem.

I vote we close this ticket.

**Comment by mitar** [comment]
Sorry, but having forms inside CMS is pretty common. Django CMS should provide some reasonable way to handle this without hacks and in a secure way. Not all forms needs canonical URL, and even if they do (like contact form) there is still CMS content around it one would like to be edited through Django CMS so that non-tech people can edit it.

**Comment by frnhr** [comment]
@mkoistinen Very good point about Placeholders. Ditto about REST. Still, I ended up misusing DjangoCMS and putting a form in a plugin. Not RESTful at all, but I don't want to explain the concept of REST to a designer I never even met. And it also kind of makes sense, from user's perspective, I have to admit even though I'd rather not  😕 

Anyways, here is what I ended up doing, a bit simplified for clarity:

    # cms_plugins.py:

    class MyFormPlugin(CMSPluginBase):
        cache = False
        ...
        def render(self, context, instance, placeholder):
            request = context['request']
            if request.method == 'POST':
                    form = MyForm(instance, request.POST)
                    if form.is_valid():
                        ...  #
                        raise ResponseRedirectException(HttpResponseRedirect('/somewhere/nice/'))
                else:
                    form = MyForm(instance)
            context.update({
                'form': form,
            })
            return context

    # forms.py:

    class MyForm(forms.Form):
        instance_id = forms.IntegerField(widget=forms.HiddenInput)
        ...
        def __init__(self, instance, data=None, *args, **kwargs):
            """ Only handle POST if instance_id fields match """
            data = data.copy() if data else None
            instance_id = data.get('instance_id') if data else None
            if instance_id == str(instance.id):
                data['instance_id'] = str(instance.id)
            else:
                data = None
            super(MyForm, self).__init__(data, *args, **kwargs)
            self.fields['instance_id'].initial = instance.id

    # middleware.py

    class ResponseRedirectException(Exception):
        def __init__(self, response):
            assert isinstance(response, HttpResponseRedirectBase)
            self.response = response
       
    class ResponseRedirectMiddeleware(object):
        def process_exception(self, request, exception):
            if isinstance(exception, ResponseRedirectException):
                return exception.response

As mentioned, this is not very efficient, since the redirect happens during render phase, and the rendered plugins before this one are wasted (because redirect happens). But hey, it works!

I'm definitely not advocating this approach, it feels kind of abusive to DjangoCMS. But I definitely think there is a need for _some_ approach to be had.

I see a few potential issues with other approaches.

The Placeholders in apphooked pages are limited to one form per page. Also they complicate things when users want to "just add a form".

Having a "canonical" form view, and possible plugin-forms that do POST to that canonical URL is probably best option of all. Though in practice, invalid forms would render on that canonical page and not where user submitted it, which might be confusing to some. This could probably be worked around by saving validation errors (or even form data) to session and redirecting back. But this approach gets complicated fairly quickly, as you pointed out.


------

I completely appreciate that you don't want to implement a whole other "view" layer on top of CMS plugins. Still, perhaps an early hook would work? Pretty much the same workflow as above, just doing form login in `that_new_hook()` instead of in `render()`, as to avoiding the wasted work. And we could presumably leave the cache on, too. Perhaps such a hook exists and I'm just not aware of it?

**Comment by mkoistinen** [comment]
I think you found a pretty nice solution given your constraints. Was AJAX not an option? It would feel a lot cleaner if it was all AJAX driven, and it would provide a nicer experience for the end-user (fewer page loads). Regarding the ability to put multiple forms on the same page, flexibly, I agree that plugins may have a place to play here.

So, as an alternative to your implementation, which I find has a lot of parts and has some draw-backs that you've already pointed out, I just put together another solution here: https://github.com/mkoistinen/cmsplugin-form-handler
Its pretty well encapsulated, extensible, non-intrusive, avoids rendering the page for no reason and has no middleware to install. I've also created a proof-of-concept project which you can download and run here: http://cl.ly/1m0z200E3F2i/download/poc.zip.
You need to create a virtualenv. I used Python 3.4 as my interpreter, but I tried to use 2.x compatible syntax. (Note I did not try to run under 2.x), then install the requirements `pip install -r requirements.txt`, then it should just work using `./manage.py runserver`. The admin login is `admin` and her password is `password`. You'll see a "Home" page which you can ignore, a "Form" page, which has a plugin-based form which asks the user for a name and hat size. The hat size has a `min_value` of 10 and `max_value` of 20 which is enforced in modern browsers. Also, there's a `clean_hat_size` method that will raise a validation error if the hat size entered is not an even number. This makes it easy to see how validation failures are handled. On success, you'll be redirected to the "Success" page. It just works, requires zero modifications to the CMS and is pretty easy to use. It is only a PoC at this point, but I think this is quite usable now. It probably needs some Python 2.7 love and avoid clobbering other-packages url parameters, but these should be easy PRs.

**Comment by frnhr** [comment]
Nice!

A few cons (just pointing them out, fully aware that this is only a PoC):
 - I instinctively cringe on seeing form data in URL query 😃   - but it can be easily altered to send the data some other way, perhaps piggyback on the `request`. Perhaps we can even piggyback the whole `form` object, to avoid instantiating it twice... I'm worried that I'm not seeing some downside of this - are there any?
 - Not sure how reliable HTTP_REFERER really is (in terms of being there) - but of course the we can pass the URL along with the form data, or possibly (?) get the URL from `instance`

Some important pros too:
 - this looks fairly "AJAXable", having its own dedicated view
 - no wasted rendering, of course, and quite a bit simpler, as you pointed out

----

Re why not AJAX - well, KISS for one. Also, I actually needed the redirect / reload, so it seemed like too many hoops to do POST over AJAX and then redirect via JS, and also render validation errors... Call me lazy, I guess. Also, progressive enhancement and compatibility with [lynx](https://en.wikipedia.org/wiki/Lynx_(web_browser)) FTW :)

**Comment by mkoistinen** [comment]
We can probably POST the data back to the form, which will get the data off the URL. this will solve other issues as well. And yes, the source URL could easily be added to the form data.

I don't know how "dedicated" the view is. I intended it to be generic in that it can support handling forms from any number of plugins, but still, it wouldn't take much for this view to understand AJAX and handle that too. PRs welcome! =)

**Comment by mkoistinen** [comment]
Just made an update to https://github.com/mkoistinen/cmsplugin-form-handler. It now uses sessions to pass data back and forth if possible, otherwise, fallsback to GET as before. Also, no longer uses HTTP_REFERER, supports both forms.Form and forms.ModelForm, better encapsulation, better "docs" (README) and much more. Fun little project, really.

**Comment by mkoistinen** [comment]
@mitar does the above package/approach help you? Can we close this now?
