### ISSUE TITLE
Page Permissions Per Language

### ISSUE THREAD

**Issue by yardenst** [divio/django-cms#2259]
It's a very common scenario to have a different user editor per language.
So it is very important to grant a permission for a user to make changes for a page only for a certain language.
As for today, this option is not available.

(original question about this issue was asked in Stackoverflow http://stackoverflow.com/questions/19198135/django-cms-permissions-per-language)

**Comment by Moini** [comment]
Hi - is there anything we can do to help? We'd also be very interesting in getting this to work.

**Comment by yakky** [comment]
Per-language editing permission should be feasible, even if it will require a lot of low-level checks as we cannot really leverage django built-in checks to do this.
Needed steps are:
- add language permission to ``cms.models.AbstractPagePermission``
- implement checks in the toolbar to show / hide live / draft mode according to the language and permission
- implement the checks in cms.admin.PageAdmin (for the basic and advanced form) and cms.admin.PlaceholderAdmin (for the plugins)

This might be scheduled after 3.1 release (due in a couple of months), but any suggestion, patch or contribution is very much welcome

**Comment by Moini** [comment]
Silly question: what would have to happen to the history? Would it have to be deactivated for translators because of permission conflicts then? 
Or can it be separated on a per-language basis, so translators can only revert changes to their own language? Or wouldn't that make any sense at all?

Currently, it's mixed-language, and doesn't show which language version was edited, which causes problems for us, as it is hard to know what one is reverting to, and it does not only revert changes to the language one is currently editing, but also removes all other progress by other translators made in the meantime (to the drafts only, not sure if that might be a special setting on our website, as we also have a not-yet-fully-ready "view diff" feature in the history).

**Comment by yakky** [comment]
Reversion format must  be also changed in this case, data is saved per language anyway (page, title and plugins are different records, eventually sharing the same revision_id)
But eventually changing the serialisation format is not a big deal, as one of the next big goals would be to refactor the current implementation of the reversion code and I don't think that dropping old history is a real issue when upgrading to a newer non-patch release

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/2259 (conversation can continue)
