### ISSUE TITLE
CMSToolbar emits JS that may error.

### ISSUE THREAD

**Issue by kezabelle** [divio/django-cms#3110]
Relates to the noisey errors documented in #3109

If a `User` is signed in and `is_staff`, putting `?edit` into the querystring for a page which opts not to use `{% cms_toolbar %}` will do the following for every plugin on the page:
`Uncaught ReferenceError: CMS is not defined`

If the `User` is not staff, this doesn't happen. Notably that means the User may be `is_superuser` and not `is_staff` and not see the errors.

If I had to hazard a guess, I'd expect the problem starts [here](https://github.com/divio/django-cms/blob/00e6965de49db3dbb4727ad769ea8ce2aa4d46ef/cms/toolbar/toolbar.py#L48) and then somewhere down the chain `cms.middleware.toolbar.toolbar_plugin_processor` is being used (because `?edit` is `True` I guess)

**Comment by mkoistinen** [comment]
The cms requires that {% cms_toolbar %} is installed on all pages in order to work correctly. So, I'm not really sure we support cases where a page "opts not to use" it. Having said this, patches are most certainly welcome, if you have a use-case that could benefit from this.

Closing in the meantime, please do open a PR if you so desire.
