### ISSUE TITLE
Suggested solution for overriding URLs in tests doesn't work properly

### ISSUE THREAD

**Issue by robertweglarek** [divio/django-cms#3438]
I found a problem with using ```@override_settings(ROOT_URLCONF='myapp.tests.urls')``` described [here](http://django-cms.readthedocs.org/en/latest/extending_cms/testing.html#resolving-view-names).
It works when I have only 1 app using this. When I add another one I get an error saying:
>NoReverseMatch: u'namespace_here' is not a registered namespace

The solution that worked is described in [Django docs](https://docs.djangoproject.com/en/1.6/topics/testing/tools/#django.test.SimpleTestCase.urls):
```
class TestMyViews(TestCase):
    urls = 'myapp.test_urls'
```

**Comment by lddubeau** [comment]
According to Django's documentation doing `@override_settings(ROOT_URLCONF='x')` is exactly the same as adding `urls = 'x'` to the test class. 

However, the issue reporter here used `'myapp.tests.urls'` in one place and `'myapp.test_urls'` in the second place. Given this discrepancy, and having successfully converted test cases that used `urls` to use `@override_settings`, I'm not convinced that there *is* a problem to be solved in Django CMS or its documentation.

Moreover, `urls` is [deprecated since Django 1.8](https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.SimpleTestCase.urls) so the long term solution is to use an override with the correct value.

**Comment by yakky** [comment]
@lddubeau agree. @robertweglarek any further input on this? otherwise I'm going to close it

**Comment by yakky** [comment]
Closing this due to the lack of feedback
