### ISSUE TITLE
Possibly wrong test

### ISSUE THREAD

**Issue by ojii** [divio/django-cms#3542]
Working on #3516 I found a test that kept failing regardless what I tried. The test in question is `cms.PluginstTestCase.test_remove_plugin_not_associated_to_page`. 

At https://github.com/divio/django-cms/blob/2fa7c67818df7e5379c19d1186dc012a2f2bde80/cms/tests/plugins.py#L540 it does a request to `add_plugin` with a POST parameter `placeholder`. However, this is wrong, as it should be `placeholder_id`. Thus it gets a 404 because it hits https://github.com/divio/django-cms/blob/2fa7c67818df7e5379c19d1186dc012a2f2bde80/cms/admin/placeholderadmin.py#L220-L221 but looking at the test name, this doesn't seem to be what it **should** be testing.

I've originally written the test, and back then `PageAdmin` wasn't allowed to edit any placeholders that are not associated with a `page`, and this test is there for that. See https://github.com/divio/django-cms/commit/cfe8341dc6b21d09d38c9b71032b4aa55a1f5b37. It however feels like this is simply wrong now.

Should this test be removed? Anyone know what's going on?

**Comment by Aiky30** [comment]
@yakky @FinalAngel The PR submitted as part of this issue was never merged, it was closed. Do you think this issue is still valid?

**Comment by FinalAngel** [comment]
@Aiky30 given that this issue is that old I suggest to close it

**Comment by Aiky30** [comment]
Hello @ojii 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
