### ISSUE TITLE
jQuery undefined in pages admin

### ISSUE THREAD

**Issue by mobula** [divio/django-cms#3725]
I'm getting the following error when browsing the pages admin: 

    Uncaught TypeError: undefined is not a function  tree_component.js:476 

I'm trying to get django-cms working along django-grappelli, which defines [django.jQuery](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/static/grappelli/js/grappelli.js#L12), which breaks [tree_component.js](https://github.com/divio/django-cms/blob/master/cms/static/cms/js/jstree/tree_component.js).

A fix I found was to simply move the *[load jstree](https://github.com/divio/django-cms/blob/master/cms/templates/admin/cms/page/tree/base.html#L32)* block after loading [cms.base.js](https://github.com/divio/django-cms/blob/master/cms/templates/admin/cms/page/tree/base.html#L37) in https://github.com/divio/django-cms/blob/master/cms/templates/admin/cms/page/tree/base.html:
 
    
    
    <script src="{% static "cms/js/modules/jquery.ui.custom.js" %}"></script>
    <script src="{% static "cms/js/modules/cms.base.js" %}"></script>
    <script src="{% static "cms/js/modules/cms.changelist.js" %}"></script>
    
    <script src="{% static "cms/js/jstree/_lib/_all.js" %}"></script>
    <script src="{% static "cms/js/jstree/tree_component.js" %}"></script>

I'm not too comfortable with all those jQuery noConflict dependencies, but that seems relatively safe, and could help with other modules that may define django.jQuery.

Side note: I think it could be nice to make jQuery and jQuery UI urls / loading configurable. Would allow to load them from CDN instead, and not have different versions loaded in the same page by different apps.

**Comment by jrief** [comment]
As a developer I'm not a big fan of a CDN solution. This is because the software shall be self-contained and runnable without requiring any connection to the Internet.

On the other side, I also dislike the bad practice to add files into your own repository, which are revisioned in another repository.
Therefore my suggestion is to add a file ``bower.json`` to the repository. It contains all the non-Python dependencies in a reproducible manner.

A developer cloning ``django-cms`` from GitHub, then must checkout these external dependencies with ``bower install --require``. For normal installations, these files safely can be added to the egg or wheel package.

Side note: In https://github.com/jrief/djangocms-cascade first I started with adding external JS/CSS to my repo. Then I moved over to a CDN solution and had big trouble during development when I was without Internet. My final approach to the problem is to use the http://bower.io/ solution.

**Comment by johnraz** [comment]
@mobula : I think your work around is safe enough, not 100% sure though, didn't follow latest front-end development. But AFAIK, it is a known fact that the project is not compatible with grappelli.

Regarding the CDN topic, sorry @jrief but I disagree, usage of a CDN has nothing to do with development and access to a connection ... The fact that you don't use a CDN when developing (which is what I do as well) shouldn't stop you from using one when going in production. Having an *option* to link to a CDN version of the big common libraries used in the project like jquery makes total sense.

Though I agree that having an external tool for fetching dependencies in development mode, keeps your git history safe from big static files diffs you don't care about.

**Comment by jrief** [comment]
@johnraz I'am not opposed to CDNs. But it still is more important to have a self-contained app. With a bower.json file this is possible; referring to files located on a CDN it is not. Consider, that some CMSs are located in Intranets with no access to a CDN.

If you can show us a DRY solution where you can switch between files hosted locally and the *same* files hosted on a CDN, I'd be very interested. Unfortunately I didn't find any.

Since bower used GitHub to download the packages, maybe we could use that information to refer to the corresponding file via https://rawgit.com/. But I haven't found any app yet.

BTW: django-bower is not an option.

**Comment by johnraz** [comment]
Well, important it is for your specific use case, but there are plenty of scenarios where relying on a CDN is more important than relying on a local file, especially for high traffic websites.

Html5 boilerplate shows one solution here, for jQuery: https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html#L25

Bower doesn't specifically use github to download its file ... it uses whatever is referenced in the bower.json file, and can be as unreliable as any link on the web ;-)

Anyway, having js files uncompressed and not concatenated in production is definitely not a best practice. Having plenty of files loaded separately should be avoided.

**Comment by mobula** [comment]
I like approaches such as that used in https://github.com/dyve/django-bootstrap3/blob/develop/bootstrap3/bootstrap.py

**Comment by jrief** [comment]
@mobula 
> bower.json seems like an interesting approach, but I'm not familiar enough with it (it obviously hasn't been adopted in the Django world).

Using bower.json in Django projects is very straight forward and I do it all the time. Here is how it works:

In the project's ``settings.py`` add

```
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    ('bower_components', os.path.join(PROJECT_ROOT, 'bower_components')),
)
```

Then in all templates, includes externally manages files with something such as
```
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
```

By keeping a bower.json file in your repository, you can avoid to add files to your repository which have been revisioned by another package. The latter by the way, is an anti-pattern in software development.
