### ISSUE TITLE
Feature request: prevent concurrent editing

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#3774]
Hi again ;)

At inkscape.org, we sometimes have more than one person trying to edit a page, although we know about the problem and try to prevent it.
We also know that there are django apps which are made for preventing this (https://www.djangopackages.com/grids/g/concurrentp-edit/).

But, according to Martin Owens, those apps are problematic for us to use.
Quote: "Most of the models require extra fields to be added, this is hard for models we don't have direct control over and thus is something that upstream django-cms must do [ when we want to use it ]".

Is it possible that you can add functionality for preventing concurrent edits?

**Comment by evildmp** [comment]
Hard to do, and very hard to do well.

The way I would do it is this:

Every admin/frontend editing form that wants to be aware of users will have some JS in it that pings the server once every few seconds with a query that contains the content type and id of the object being edited.

This will include every object that might be saved by the form - including those in inlines, so possibly many objects will be pinging the server with this query. (Of course, some objects will also affect other objects that aren't present in the forms (e.g. in `save()` methods) and it would be extremely hard, sometimes impossible, do know what they all are. But this is rarer, in most cases, especially for the CMS.)

When the server is pinged with these queries it will return information about any other forms that are also pinging it, and this can be displayed in the forms, to alert users - either that someone else is has already has the forms open, or that someone else opened one after you did. 

If necessary, it could even prevent a save until the first person has closed their form.

I don't think this system would require any extra fields o the models, because it's all form-oriented.

The human problems are also hard to solve. It's a pain in the neck if someone forgets to close the form and goes to lunch, for example.

The whole thing looks pretty complex to me.

**Comment by Moini** [comment]
"The human problems are also hard to solve. It's a pain in the neck if someone forgets to close the form and goes to lunch, for example." 
- maybe a timeout that can manually be reset by the person who is editing could help? People will learn fast enough that work is lost if they don't save and leave ;)

**Comment by mkoistinen** [comment]
Another approach could be that on "Save", the Admin (class, not person) first just verifies that the object hasn't already changed since the local change-form was first opened (either by comparing all fields, or just a single timestamp field) and if it has, indicates which fields have "collisions" and presents a dialog warning the operator of the situation allowing them to override, reload the other operator's changes, or simply cancel. Seems that this is an extensible approach that doesn't require a lot of real-time messaging.

**Comment by evildmp** [comment]
See also https://groups.google.com/d/topic/django-developers/mOkvOQQGhJk/discussion

**Comment by thoreg** [comment]
This topic came up again and was discussed (even if not deep) here: https://plus.google.com/+ThomasRega/posts/CtrBnjKvJzQ

**Comment by Moini** [comment]
Thank! :D 

It's very important for us that this will work with translations. I'm not in a position to test this currently, but if someone tests the pr, could they please also test if translators can work in parallel on two different translations?

**Comment by bartTC** [comment]
Hi, we stumbled over this issue as well and I can see the complexity to integrate this well on page/transaction level.

What about drastically simplifying this, do not lock a page, and make it much more high level. I could imagine a notification  "User xx is currently editing this page too." which then is discarded in cache once the page was published, edit mode is closed, a timeout ran out.

**Comment by FinalAngel** [comment]
Closing for further discussions in:
https://groups.google.com/forum/#!topic/django-cms-developers/MIhUzcQpWrg
