### ISSUE TITLE
develop.py test --xvfb option not documented

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#3790]
This tip from the developers mailing list isn't documented:

"If you have some sort of X installed, you can `pip install xvfbwrapper` in the venv and run the tests with `--xvfb` and they won't need a physical display."

Any reason not to do so?

**Comment by yakky** [comment]
No reason :)
Actually just a general lack of documentation on how develop.py works 
Related to #3783

**Comment by dirtycoder** [comment]
I wish to do it but...

Where is the best place to insert it? Maybe after the "Getting the source code" section in the Contribution doc?
Also, as this is target to 3.1 and 3.1.x I should wait for a support/3.1 branch or base this on the develop branch?

Thanks.

**Comment by yakky** [comment]
@dirtycoder thanks for your availability. I'd add a section before "Running and writing tests" called "The develop.py command" so that all the options can be properly documented
You can use http://django-cms.readthedocs.org/en/develop/reference/cli.html#command-line-interface as a template for styles and strcuture.
target develop as 3.1.1 will still be developed from it

**Comment by dirtycoder** [comment]
Thanks, I will take a look at it in the weekend.

**Comment by dirtycoder** [comment]
There's already a section after "Running and writing tests" covering some options for develop.py, I think it makes more sense to move it all to a separated page focusing on develop.py only.

Let me know if I can do it.

**Comment by yakky** [comment]
Fixed in #4073
