### ISSUE TITLE
Error installing aldryn-blog

### ISSUE THREAD

**Issue by dossan** [divio/django-cms#3806]
(_I have also asked this in the django-cms tutorial github issues page._)

I am following the tutorial from the django-cms official website, but I am having a problem installing _aldryn-blog_ using _pip_ (Step 5 - Installing A Blog App). This is the output when I try to install aldryn-blog:

    Collecting aldryn-blog
      Using cached aldryn-blog-0.4.6.tar.gz
    Collecting django-taggit<0.12 (from aldryn-blog)
      Using cached django_taggit-0.11.2-py2.py3-none-any.whl
    Collecting django-filer (from aldryn-blog)
      Using cached django-filer-0.9.9.tar.gz
    Collecting django-select2 (from aldryn-blog)
      Using cached Django-Select2-4.2.2.tar.gz
        Traceback (most recent call last):
          File "<string>", line 20, in <module
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
          File "<string>", line 20, in <module
    
        ----------------------------------------
        Command "python setup.py egg_info" failed with error code 1 in ...

I am on the virtual environment.

Since I quite newbie to django-cms, I really don't know what could be the problem, except that the output is talking about a _**string**_ file...

**Comment by jsma** [comment]
Should the django-cms docs instruct users to install any aldryn-* apps at the moment? I just helped steer a user on IRC away from these since the aldryn-* apps do not appear to be compatible with Python 3 even though django-cms and core plugins are. I documented some issues in [this post on the users mailing list](https://groups.google.com/d/msg/django-cms/lX8vS_aG6aU/jzfvz1RG45UJ). 

I don't think we should steer the community to these plugins at the moment.  In general the aldryn-* apps seem to be tightly coupled to poorly written/maintained apps rather than being apps that just do one thing well.

The specific error mentioned by the OP is due to django-select2 using print statements without parenthesis in the setup.py so it breaks for Python 3 users.

**Comment by mkoistinen** [comment]
@yakky, I see this is tagged for component: configuration, but also for 3.0.10. It isn't entirely clear what changes should be made to the CMS for 3.0.10 here.... is this a documentation issue?

**Comment by yakky** [comment]
@dossan is the virtualenv a Python3 one?  aldryn-blog is not python 3 compatible AFAIK
@mkoistinen error on my side: probably a tick too much

**Comment by mkoistinen** [comment]
Still not clear to me what is actionable on the django-cms side. Can someone make this clear?

**Comment by yakky** [comment]
@mkoistinen agree. Closing this as it's not really related to django CMS
@dossan reopen on aldryn-blog if this happens on python 2 environment
