### ISSUE TITLE
Some cms tags are not recognised by PyCharm

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [divio/django-cms#3878]
Some cms tags are not recognized by PyCharm, because during the registration no explicit name has been assigned.

Example cms v3.0.10: cms_tag.py line 535: register.tag (PageAttribute)

If the following line is added everything is OK:
register.tag ("page_attribute", PageAttribute)

Why some tags are registered twice? One with and one without a name.

**Comment by mkoistinen** [comment]
Hi @Arne-Pfeilsticker! I suppose this would be nice to have since a number of us use PyCharm. However, as you can imagine, our goals isn't necessary to cater to one IDE or another. Having said this, if the capability is there in PyCharm, and we can exploit it, why not? It should make a great first PR to the project for someone. Are you interested in tackling this?

**Comment by Arne-Pfeilsticker** [comment]
Hi Martin,
sure.

After I reported the bug, I've noticed that other template tags in other files are registered without a name parameter, too.

That's why I opened a issue with JetBrains so PyCharm will be changed. I hope so.  https://youtrack.jetbrains.com/issue/PY-15105 <https://youtrack.jetbrains.com/issue/PY-15105> 

What I do not understand is why some registrations are made twice. One with and one without a name parameter. Do you have an explanation for this?

If you want, I would be glad to go through the template tags files and change the register.tag function calls uniformly.

You'd have to help me briefly in the procedure:
1. Fork django-cms
2. Apply changes.
3. Pull request

That's all? Or what about tests?

> Am 19.02.2015 um 01:14 schrieb Martin Koistinen <notifications@github.com>:
> 
> Hi @Arne-Pfeilsticker <https://github.com/Arne-Pfeilsticker>! I suppose this would be nice to have since a number of us use PyCharm. However, as you can imagine, our goals isn't necessary to cater to one IDE or another. Having said this, if the capability is there in PyCharm, and we can exploit it, why not? It should make a great first PR to the project for someone. Are you interested in tackling this?
> 
>

**Comment by mkoistinen** [comment]
Arne,

The reason why some are registered multiple times, for example here: https://github.com/divio/django-cms/blob/develop/cms/templatetags/cms_tags.py#L625-L626, is because sometimes, we register the tag a second time with a different name. There are different reasons for why we do this; deprecation period of the old name is common, but it could also be that the tag acts differently depending on the name used to call the tag (not sure if there's any examples of this).

We usually register the first time without a name, because the registration process can take the "name" from the name property of the tag itself. This is the preferred way to do it because it is DRYer. In cases where you need to register a tag with a name different than the tag's name property, you need to set the name as a parameter to register.tag() at registration time.

I strongly recommend you review our docs for contributing to the project starting here: https://django-cms.readthedocs.org/en/support-3.0.x/contributing/index.html this should cover the whole process including testing, etc.

In general, here's the process:
1. Fork django-cms to your own github account;
2. Clone your fork to your own machine;
3. Checkout a new branch such as 'arne-pfeilsticker-feature/fix_3878' or whatever;
4. Make your changes;
5. Test;
6. Publish your new branch to your own github repo;
7. By magic, GitHub will allow you to create a Pull Request to the official repo from your branch;
8. Wait for someone to review and reject, or hopefully, accept and merge your branch.

Hope to see your PR soon!

**Comment by FinalAngel** [comment]
@Arne-Pfeilsticker did @mkoistinen comment solve your issue?

**Comment by czpython** [comment]
Closing as duplicate of https://github.com/divio/django-cms/issues/5663
