### ISSUE TITLE
copy_relations() does not work for relations between cmsplugins

### ISSUE THREAD

**Issue by philippze** [divio/django-cms#4143]
In the docs, there's a recipe for [handling relations](http://docs.django-cms.org/en/develop/how_to/custom_plugins.html#handling-relations) in custom plugins.

However, this will not work when we deal with relations from one cmsplugin to another cmsplugin.

I've written four unittests [here](https://github.com/philippze/django-cms/commit/658e67f41f9029443ed3fe36d268ef09ef5e2644). Two pass and show that the docs is correct in usual cases. Two fail and show that it's not so simple for relations between cmsplugins.

Maybe one could mention this in the docs.

I'm now writing a little module that solves the problem for ManyToManyFields. Existing solutions welcome!

**Comment by yakky** [comment]
Thanks for the awesome tests and a very well described issue.
The problem with ``copy_relations`` between plugins is that while the ``copy_relations`` in https://github.com/philippze/django-cms/commit/658e67f41f9029443ed3fe36d268ef09ef5e2644#diff-f813663252f41cc6f43485a6b06e7caeR58 will work when copying the ``PluginModelWithM2MToModel``, there is no (general) way for the target plugin to change the reference from the "draft" to the "live" version of itself in the referencing plugins.
I think we can just document this.

**Comment by evildmp** [comment]
@yakky @philippze Should we not also incorporate at least the passing tests and keep this open until a more general solution is available?

**Comment by yakky** [comment]
@philippze I totally second @evildmp proposal. Could you open a PR?

**Comment by sergei-maertens** [comment]
Another use this case that fits this issue is re-using plugin content.

We have a specific use case where the end-user adds a 'Story' plugin to a certain page. It has some images, a bit of text, and nested plugins for the body of the content.

On the homepage, they need to be able to refer to this very same story, and if the initial story page (and plugin) gets updated, the homepage version has to be synced as well.

Currently this is solved by letting the `HomepageStoryPlugin` link (via FK) to the draft version of the `StoryPlugin`, but that obviously has its drawbacks.

**Comment by mkoistinen** [comment]
@philippze someone else had a similar need and I put together a sample plugin for them. Perhaps this will help you too? https://gist.github.com/mkoistinen/403a81c05b4b8f783c74 and a video demo of this plugin in action: http://cl.ly/332q3R42202X/draft-public-plugin-demo.m4v

**Comment by philippze** [comment]
Hi @mkoistinen Thanks for this useful hint! I've started to write a djangocms-relations plugin in the Christmas holidays, but unfortunately did not have any time to continue since. The plugin starts with the same idea as the HighWaterMarkPlugin. In case anyone would like to contribute, they're welcome [here](https://github.com/philippze/djangocms-relations)

**Comment by mkoistinen** [comment]
I've been seeing similar "issues" lately as people seem to think that CMSPlugins should be the basis of all business logic. I think we can probably do a lot with some clearer guidance in the documents about what CMSPlugins are for and what they're not for.

**Comment by philippze** [comment]
I'm now setting a deadline for myself. My module that simplifies relations with CMSPlugins should be ready in 2 weeks.

**Comment by czpython** [comment]
Closing as the original issue was addressed in 31ac39fc0d4959eae98a21ae8b834747592e483f and  https://github.com/divio/django-cms/pull/4466

**Comment by corentinbettiol** [comment]
*Replying to this issue since it spawns in Google for "djangocms cmsplugin relations":*

We created a custom relation between `class 1` and `class 2` using a new class and `uuid` (the uuids are the same for the draft & live version of each plugin for each class) to be able to add ids of `class 1` in `class 2` in the `copy_relations` function of `class 1` when the page containing an instance of `class 1` is published.

Here's a bad drawing of the solution:

![image](https://user-images.githubusercontent.com/45763865/120482754-b77d4500-c3b1-11eb-9a49-afac40e4b4d8.png)

*The solution was implemented in [djangocms-faq](https://gitlab.com/kapt/open-source/djangocms-faq), see [those lines](https://gitlab.com/kapt/open-source/djangocms-faq/-/blob/master/djangocms_faq/models.py#L126-134) for the creation of the relation, and [these ones](https://gitlab.com/kapt/open-source/djangocms-faq/-/blob/master/djangocms_faq/models.py#L59-62) for the update.*
