### ISSUE TITLE
Using request.current_page in shared templates (headers/footers etc) (question)

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#4335]
Over time I've built a few extensions to the `Page` and also used `request.current_page` to get page titles etc. For example...
```
     {% if request.current_page.get_ancestors|length <= 1 %}
         <section id="content"
                  class="{{ request.current_page.pagecolourextension.page_colour }}">
```
This allows a page to have a colour assigned to it from the toolbar & sits in our base template.

During some recent load testing it became apparent that we were getting a lot of database hits where `request.current_page` wasn't set. I believe this was happening where the base template was being used by a view from an app hook. I know this is bad practice, so is there an alternative attribute of the request object that identifies that we're within an app, or a better way to implement a `request.current_page` context variable or similar?

**Comment by yakky** [comment]
``request.current_page`` is retrieved in a single query (a simple get(pk) -https://github.com/divio/django-cms/blob/develop/cms/appresolver.py#L50- in case of an apphook, a slightly more complicated one -https://github.com/divio/django-cms/blob/develop/cms/utils/page_resolver.py#L64- in the case of normal pages)
You can eventually use the ``depth`` page attribute to find out the depth of the page instead of get_ancestors.
Are you able to trace the extra queries triggered by the above code?

**Comment by FinalAngel** [comment]
@marksweb is this still relevant to you?

**Comment by marksweb** [comment]
I'll close this one.
