### ISSUE TITLE
Admin pane at page edit page is being refreshed - probably, too often

### ISSUE THREAD

**Issue by otg-sandrey** [divio/django-cms#4538]
In the admin interface while editing a page content the user can open an admin pane at the left side of the window.

In our scenario, the user opens the admin pane and open the pages structure view there. He/she click the site name at the top menu, and chooses "Pages".

The problem is that this pane is being refreshed from time to time. It looks like the admin frame is being reloaded.

In installations with many pages (we have ~1000 with ~50 at top level) it takes time. Users complain that it is really inconvinient and disrupts thier work. People tend to expand the admin pane to full screen, and like to work with the pages structure in this full screen mode. Reloading happens without any notification and all of sudden, for instance, while you are moving a page from one branch to another.

What are the reasons behind the reloading of the admin pane? Is it a bug of a feature? Is there a way to disable the reloading?

django-cms==3.0.14

**Comment by yakky** [comment]
@otg-sandrey there is no autoreload for the sidebar panel. does any message appear in the browser console?

**Comment by FinalAngel** [comment]
@otg-sandrey can you provide us with additional Information such as browser and system version? As @yakky mentioned, this should not be the case. Eventually some timeout is behaving bad or there is a conflict with an addon installed within the browser.

**Comment by otg-sandrey** [comment]
I can't reproduce the problem in my system but end users keep complaining. Will get more information shortly.

Are there any updates notifications sent from the server to a web browser where the sidebar panel is open? Which might force the admin UI to refresh the sidebar because somebody else is changing the site pages structure?

**Comment by vxsx** [comment]
> He/she click the site name at the top menu, and chooses "Pages".

So I'm assuming we are talking about the sideframe. If the user moves the page that is a parent of the current page (or the current page) in the tree (so path of the page the user have currently opened has changed) then the page will reload with this new url, in turn reloading the page tree in the sideframe.

E.g. I have this tree:
```
/foo
    /bar
        /baz
/xyz
```
and i'm currently on `/foo/bar/baz`. if the `bar/baz` branch is moved onto `/xyz` we redirect on success (because the url we are currently on doesn't exist anymore).

This is the only case I remember where we reload the page tree. However in order to get this "redirect" signal you have to explicitly trigger a successful move. 

the code that triggers the check https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.changelist.js#L243
and then it goes here https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.base.js#L79

**Comment by FinalAngel** [comment]
Can the end user clear their localStorage eventually and try again @otg-sandrey. A good advise is also to disable browser addons as they might interfere.

**Comment by FinalAngel** [comment]
This seems to be fixed in 3.2 as we also did improvements on the iframe reloading.
