### ISSUE TITLE
Overlay mode: previous/next/close buttons make 'Add page' unreachable

### ISSUE THREAD

**Issue by Moini** [divio/django-cms#4985]
The new large buttons to navigate the admin interface in overlay mode are placed directly above the 'Add page' button (I know about the new wizard).

![bildschirmfoto_2016-02-06_00-03-32](https://cloud.githubusercontent.com/assets/3240233/12867704/dd60b612-ccf4-11e5-89da-e5b08bf4b9b2.png)

Django 1.8.7., Django-cms 3.2.0

**Comment by FinalAngel** [comment]
@Moini we recommend using djangocms-admin-style that is also referred in the installation instructions for optimal results: https://github.com/divio/djangocms-admin-style

**Comment by doctormo** [comment]
A recommended extra should be properly labelled as required in the dependencies. Otherwise it risks giving the impression that django-cms can functional without djangocms-admin-style

If the intention is that django-cms should be functional without admin-style, then the bug here is valid. (although maybe not as important to djangocms-admin-style using developers) which is fine, makes it harder to get the fix from djangocms maintainers. But that doesn't mean this bug report should be closed, what if someone else wanted to fix it?

**Comment by FinalAngel** [comment]
Hello @doctormo I share your concern.

Technically, the problem here is, that we do not know which admin-style gets rendered in the background  so we can't modify that elements CSS. We provided additional classes for theme creators to control that behaviour. It can now be fixed either at the admin-theme level (which would be Django) or yourself within the project. The class pattern is:

``.cms-sideframe-close`` & ``cms-sideframe-history`` and within the iframe: ``.cms-admin-sideframe``.

**Comment by Moini** [comment]
I've now just pushed down the breadcrumbs by adding a 10px padding to them...
