### ISSUE TITLE
Password reset on Login bar

### ISSUE THREAD

**Issue by djorgesen** [divio/django-cms#5057]
In stock django project there is a password reset link, if a url named 'admin_password_reset' exists,
The relevant code is here at  `django/django/contrib/admin/templates/admin/login.html`
on line 55.
```html
{% url 'admin_password_reset' as password_reset_url %}
{% if password_reset_url %}
    <div class="password-reset-link">
        <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
    </div>
{% endif %}
```
I would like to add this or similar code to the Toolbar login at `cms/templates/cms/toolbar/items/login.html`
so that if you have set up your project to allow users to reset their passwords, they have access to this function.

**Comment by yakky** [comment]
@djorgesen thanks for suggesting this
@divio/django-cms-core any comment on this proposal?

**Comment by czpython** [comment]
@yakky While I agree that the error is not urgent, I think the current behavior is correct and in alignment with the way django's admin and cms plugins handle such a scenario.

As far as I understand it, a duplicate wizard can only happen due to a programming error and so it should fail on startup (just like the admin).

**Comment by czpython** [comment]
:+1:

**Comment by czpython** [comment]
Closing as this fits our feature request criteria.
If you're still interested in this feature, please create a topic in the [Developers Mailing List](https://groups.google.com/forum/#!forum/django-cms-developers).
