### ISSUE TITLE
Migration 0005 doesn't use selected database

### ISSUE THREAD

**Issue by doctormo** [divio/django-cms#5093]
When trying to create a new database via syncdb (or migrate) we get the following error:

  File "/home/doctormo/www.inkscape.org/pythonenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/doctormo/www.inkscape.org/pythonenv/lib/python2.7/site-packages/MySQLdd/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1054, "Unknown column 'cms_page.level' in 'field list'"

The command was `manage.py migrate --database=local` and the local database is a postgresql database. But the error above looks like it's trying to contact the mysql database (which is 'default')

**Comment by jmelett** [comment]
I had the same issue when having two different databases (MySQL and PostgreSQL) - the fix was to remove the MySQL DB temporary (by commenting out the entry).

**Comment by naush** [comment]
Same problem here.

We have a test database that we use `--database=test` to select based on [instruction](https://docs.djangoproject.com/en/1.7/topics/db/multi-db/#synchronizing-your-databases) from official docs. However, 0005 picks up default database instead. And because 0006 (which removes the `level` column) was ran on the default database already, 0005 errors out when referencing the removed column `level`.

A simple way to demonstrate this:

```py
# Edit migrations/0005_auto_20140924_1039.py
from django.db import router
using = router.db_for_write(Page)
print(using)
```

Run `./manage.py migrate --database=anything_other_than_default`.

**Comment by czpython** [comment]
@doctormo @nagyv 
I've pushed a PR to fix this https://github.com/divio/django-cms/pull/5601.
I'd really appreciate it if you could test in your setups.
This will likely land on 3.3.3 as 3.3.2 is on code freeze.

**Comment by Arany** [comment]
@czpython The fix does not seem to be merged into the 3.3.x branch?

**Comment by doctormo** [comment]
The tests did pass my end. I may have forgotten to update this issue. Sorry cz

**Comment by czpython** [comment]
I accidentally deleted the branch and thus the PR was closed.. 😭 
Will push a new PR today. Thanks for the feedback!

**Comment by czpython** [comment]
Pushed new PR https://github.com/divio/django-cms/pull/5731
This will be backported to 3.3.x
