### ISSUE TITLE
Custom content types

### ISSUE THREAD

**Issue by gRoberts84** [divio/django-cms#5123]
Hi there,

I'm sorry for asking what may be an absolutely obvious and stupid question, however I've spent way too much time trying to find out how to implement my own content types.

Is there any documentation on how I can add my own content type, i.e. Video's and Categories, which I can then view as a list or single item?

I've RTFM, multiple times but clearly i'm missing it (I'm new to Django lol..)

**Comment by yakky** [comment]
django CMS does not have any "Content type", unlike many other CMSes
You just create templates and fill in with plugins
Plugins are partially similar to content types but they are only for a page fragment http://docs.django-cms.org/en/3.2.3/how_to/custom_plugins.html

**Comment by gRoberts84** [comment]
Hey,

Thanks for getting back to me on this.

My concern is trying to implement a blog or similar which has a list and
single view.

I've come across a blog plugin but that's a little over the top.

Is this something that has plans for changing in the future?

Thanks :)

**Comment by yakky** [comment]
django CMS it's a CMS for "simple" content pages. For structured contents (like a blog ) you have to use (by design) one of the existing Django / django CMS applications (or you can build your own Django application). You can check https://github.com/nephila/djangocms-blog / https://github.com/aldryn/aldryn-newsblog for your immediate needs
