### ISSUE TITLE
Make it possible to put more than 1 plugin in the clipboard

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#5362]
At the moment when you copy a plugin or create an alias, it is put into the clipboard. However it seems the clipboard only contains the most recently copied/aliased plugin: every time you put something into the clipboard, it is first cleared. I'm not sure whether it's a bug or an expected behaviour, but in the latter case it would be nice to allow more than 1 plugin in the clipboard.

I could reproduce this on 2 different sites running DjangoCMS 3.3.

**Comment by jrief** [comment]
This relates to #5257 
The problem with more than one clipboard is, that you need an extra select button for choosing the correct clipboard. This adds a lot of complexity to the usability of the CMS. Unless you have real power users, I personally would advise against such a feature.

**Comment by FinalAngel** [comment]
The clipboard is based on "ctr + c" and "ctr + v"" philosophy where you can always have only one item stored. While it might be technically possible, it can create confusion about order and usability as @jrief mentioned. Until further demand and/or a good usable solution, this feature is not planned.

**Comment by mkoistinen** [comment]
@sephii I also find myself wishing to have this ability and the truth is, we actually had this in CMS 3.0! However, as pointed out by others, some found this confusing and we've since removed the feature in favor of simplicity. What I do now is to put the one's I wish to copy inside another. Then, copy the parent, and it will copy all of them. This is actually an advantage over what we had before, because I don't think you could copy nested plugins before.

@FinalAngel I could foresee a solution here that would work perfectly well with our current solution. Essentially, if we could support [some-modifier]-click to select multiple plugins, then copying them (ctrl-c), would copy them all. Then, ctrl-v would paste them, precisely as we do now with whole placeholders. Let's discuss.

**Comment by sephii** [comment]
@jrief why would you need an extra select button for choosing the correct clipboard? The clipboard already contains what looks like a list of plugins that we can drag'n'drop, we could just add additional plugins to the list:

![2016-06-02-212950_431x145_scrot](https://cloud.githubusercontent.com/assets/754333/15758154/87f74b34-2909-11e6-862f-58e60546d27c.png)

Also if it's not possible to copy multiple items into the clipboard (or create multiple aliases) I think at least the UX could be improved: warn when copying/aliasing a plugin if the clipboard is not empty, and display the clipboard differently (so that it doesn't look like a list).

**Comment by FinalAngel** [comment]
I'd welcome the idea to select multiple plugins and copy / paste them at once @mkoistinen /cc @vxsx . But modifying the clipboard to show more than one plugin (a history of what was copied) caused a lot of confusion and this is what I'm against.

**Comment by vxsx** [comment]
Selecting multiple plugins to copy into different place is troublesome since each plugin can have different parent / child restrictions (+ placeholder conf and per plugin restrictions), so copying multiple ones at once is not a guarantee that they can be pasted in a different place (even at the same nesting level), and it can get pretty complex real quick. We wanted at some point to introduce the cmd + drag that would instead of moving the plugin would copy it to the new place (might even not go into the clipboard), but that's not the same anyways.

**Comment by jrief** [comment]
@sephii actually, in djangocms-cascade you can persist the clipboard's content in the database and give it different names. Later you can restore it to the clipboard and paste it wherever you want. This even works across different instances of django-cms, hence you can paste a subtree of plugins from one site to another.
This however is a separate functionality which only works, because cascade keeps all plugin data as serialized JSON. It does not work for generic plugins.

**Comment by mkoistinen** [comment]
@FinalAngel, @vxsx understood, and agreed.
