### ISSUE TITLE
parent_classes in CMSPlugin

### ISSUE THREAD

**Issue by piotrjakimiak** [divio/django-cms#5371]
I found possible problem in aldryn_segmentation but IMHO it's a bug in CMS.

Aldryn Segmentation plugins have parent_classes property set.

1. Create parent plugin (SegmentLimitPlugin)
2. `render_plugin` for instance is called with placeholder passed as argument.
3. Child plugins are computed (https://github.com/divio/django-cms/blob/854a4c245d77f7cf26f167409c292cca5d78fcd3/cms/models/pluginmodel.py#L185)
4. `CMSPluginBase.get_child_classes` call `plugin_pool.get_all_plugins(slot, page)`
5. Placeholder is passed so https://github.com/divio/django-cms/blob/854a4c245d77f7cf26f167409c292cca5d78fcd3/cms/plugin_pool.py#L185 is used.
6. Aldryn Segmentation child classes has `plugin.requires_parent_plugin(placeholder, page) == True` so plugins are filtered out.
7. I cannot create any SegmentPlugin inside SegmentLimitPlugin.

I think that `plugin_pool.get_all_plugins` should take plugin instance (SegmentLimitPlugin in my case) and do not filter out plugins that have parent_classes equal to given instance.

I can create PR if i'm right.

**Comment by czpython** [comment]
@piotrjakimiak 
Thanks for the report.
I can confirm this is a regression introduced in 3.3.

The fix for this is to not pass the `slot` and `page` arguments to `get_all_plugins()` in [here](https://github.com/divio/django-cms/blob/develop/cms/plugin_base.py#L502).
By default, `get_child_plugin_candidates` should operate on all registered plugins and then let the plugin itself handle the filtering. There will be room to optimize this in a later release by only calling `get_child_plugin_candidates` if it's overridden.

Given that you're right, let me know if you can push a PR with tests for this :)

**Comment by piotrjakimiak** [comment]
@czpython Fixed

**Comment by vxsx** [comment]
@czpython do we need a changelog entry?

**Comment by czpython** [comment]
@vxsx yes I plan to do once I backport
