### ISSUE TITLE
DjangoCMS now requires djangocms-admin-style>=1.0

### ISSUE THREAD

**Issue by LaurensBER** [divio/django-cms#5459]
In previous releases this was still >=0.2.

I maintain an product where we integrated the styling when it was still in the 0.2 series (that was the most recent styling available at that moment). I would strongly prefer not to upgrade the admin styling at this moment (the difference between the 0.2 and 1.0 version is quite big) due to how confusing new styling can be for users.

If I manually install the 0.2 styling after upgrading Django-CMS everything seems to work mostly fine.

Would it be possible to change this requirement in setup.py so that we (and other existing users) can still make use of all the fixes in the 3.3 release? For new installations pip will still grab the newest version so this should not lead to any regressions.

**Comment by FinalAngel** [comment]
@LaurensBER since django CMS 3.2 djangocms-admin-style >= 1.0 is highly recommended. We do not test older versions (< 1.0) for 3.2+ releases anymore. So functionality actually might break.

If you still want to use 0.2 - at your own risk - please install it manually. Any remarks @yakky otherwise closing?
