### ISSUE TITLE
New related_name triggering migrations for all plugins

### ISSUE THREAD

**Issue by jsma** [divio/django-cms#5550]
It appears that [this commit](https://github.com/divio/django-cms/commit/871a16433f713249ee20b52574803f51941ac20c) changed how the related_name is calculated per CMSPlugin subclass. If I do `./manage.py makemigrations`, it attempts to create migrations for any installed app which subclasses CMSPlugin:

```
$ ./manage.py makemigrations
Migrations for 'cmsplugin_filer_image':
  0009_auto_20160719_0239.py:
    - Alter field cmsplugin_ptr on filerimage
Migrations for 'cmsplugin_filer_file':
  0005_auto_20160719_0239.py:
    - Alter field cmsplugin_ptr on filerfile
Migrations for 'djangocms_inherit':
  0003_auto_20160719_0239.py:
    - Alter field cmsplugin_ptr on inheritpageplaceholder
Migrations for 'cmsplugin_filer_teaser':
  0003_auto_20160719_0239.py:
    - Alter field cmsplugin_ptr on filerteaser
Migrations for 'cmsplugin_filer_folder':
  0003_auto_20160719_0239.py:
    - Alter field cmsplugin_ptr on filerfolder
```

As far as I can tell, the only thing these migrations do is add the related_name attribute to the cmsplugin_ptr field. 

I didn't see any warning about this in the documentation and I don't see bugs or recent migrations added to other projects (`cmsplugin_filer_*`, etc.) so my first suspicion is that I've goofed something up or am generally suffering from lack of sleep. Apologies if so!

If this is a legitimate bug, this seems to mean that every external plugin app needs to have a new migration added and possibly will need to have point releases that are pinned to django-cms>=3.3.1. I haven't tested, but if these migrations are added to a plugin app that is then run on django-cms<3.3.1, won't migrations detect the _lack_ of a related_name attribute and want to create a migration to _remove_ it?

**Comment by czpython** [comment]
@jsma 
Hello,
Thanks for reporting.

This is a known issue, we've been discussing internally how to address it without too much effort on project developers.

So far we think the best approach is to create the migration for apps that support 3.3.0 and up meaning Django 1.8+ (cmsplugin-filer is an example). For apps that still support Django 1.6 and 1.7, we're planning to either drop 1.6 & 1.7 support or simply add the parent link field explicitly to the plugin model and specify the old `related_name`.

**Comment by jsma** [comment]
Should end users (as opposed to reusable app authors) just let `makemigrations` generate these migrations and apply them?

**Comment by stefanfoulis** [comment]
@jsma you should avoid creating any migrations in apps that are not part of your project sourcecode at all costs. Because they will end up somewhere in the site-packages of your virtualenv and only visible to that specific deployment of the project. So they can disappear again whenever the virtualenv (or docker container) is rebuilt. That would cause all sorts of annoying manual cleanup for your db (ghost migrations, unmerged migrations, ...).
And if you're developing a re-usable app in the context of such a project, a new migration in your app might depend on a migration that only exists in that one project.

**Comment by takeontom** [comment]
@stefanfoulis What's the recommended way to handle that situation? Some apps (djangocms-filer being a prime candidate) quite often don't include the necessary migrations. This has repeatedly bitten me in the ass in the ways you describe.

Is there a best practice way to handle it? Is that best practice to simply not upgrade to a version of an app with missing migrations? Or is there some way to create placeholder migrations until the app author creates the "official" migrations?

**Comment by bittner** [comment]
@czpython Re https://github.com/divio/django-cms/issues/5550#issuecomment-233622904 why not release a major version finally (1.0) of all affected plugins, conveying this is for an LTS version of Django (1.8) and up, while the 0.x versions can stay backward compatible.

If this is consistently executed over all `djangocms_*` projects / plugins then that'd be any easy rule to learn for each and every Django developer using django CMS and its plugins. - What do you think?

In any case, this is something that should be addressed very soon.

**Comment by amadornimbis** [comment]
@czpython 
> So far we think the best approach is to create the migration for apps that support 3.3.0 and up meaning Django 1.8+ (cmsplugin-filer is an example). For apps that still support Django 1.6 and 1.7, we're planning to either drop 1.6 & 1.7 support or simply add the parent link field explicitly to the plugin model and specify the old related_name.

Since this was introduced in the 3.3.1 release, shouldn't there a note in the changelog for v3.3.1 that mentions that this is to be expected? My organization maintains about 10 different CMS plugins, and to see that a new migration must be made for all of them because of what might appear at first glance to be a (semver) patch release was a little jarring. At first, I thought this was a problem with our configuration because there was no note of this in the changelog.

**Comment by czpython** [comment]
Closing as this has now been addressed in all major addons.
