### ISSUE TITLE
Aliases don't get copied correctly when using multi-language

### ISSUE THREAD

**Issue by lmanzurv** [divio/django-cms#5588]
I have a site that has pages in 5 different languages. In the home page I have 2 style plugins which I add to 3 other pages using alias (with its corresponding children). But when I copied those 3 pages to other languages using the Copy all plugins from English, the alias that gets generated is pointing to the plugins in the English homepage, not the corresponding new language's homepage.

To fix this, I have to delete all the aliases I have inserted on the different pages and recreate the alias in the language's homepage and the re-paste them where I want them so they don't point to the wrong plugin.

**Comment by czpython** [comment]
Hello @lmanzurv ,
This was a design decision.
The alias  plugin allows content managers to reference plugins regardless of their language.
Also when the alias plugin is copied it has way to know which plugin represents it's aliased plugin in the target language as plugins are not related.

I recommend using placeholder aliases instead of plugin aliases, the advantage is that the same placeholder is used for all translations in a page and so the alias of a placeholder will only render plugins in the current language.
