### ISSUE TITLE
Creating new placeholders make them impossible to edit.

### ISSUE THREAD

**Issue by prefzlu** [divio/django-cms#5614]
Hello everyone!

I'm trying to create multiple placeholders in my code, so later the admin could change various parts of my webpage easily. 

The problem is that when I create a NEW placeholder let's say something like this:

```
<div> {% placeholder "mycontent" %}</div>
<footer> {% placeholder "footercontent" %}</footer>
```

Both examples create new placeholders but I can't edit them because they're unclickable.

here: http://docs.django-cms.org/en/release-3.3.x/introduction/templates_placeholders.html

it seems that is possible to add multiple placeholders but in my case it only works  with placeholder "content".

I don't know if that the expected behavior and I'm doing something wrong or if this is a real problem when creating new pages "manually" (by code).

**Comment by czpython** [comment]
Hello @prefzlu ,
Is there any JS errors on the browser console?

**Comment by evildmp** [comment]
@prefzlu I think there is a misunderstanding here.

A placeholder doesn't create a clickable area *until there is anything in it that can be clicked* - i.e. a plugin.

We're looking at ways of making this easier to work with, but for now, it's expected behaviour. You have to switch to structure mode and place a plugin into the page before there will be anything to click.
