### ISSUE TITLE
Combined static paths in production

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#5785]
Just in the process of setting up my first production site in CMS 3.4.x and I've got some static paths from CMS admin that aren't separated. Which is stopping the page select widget from loading.

The first I've seen are coming from the advanced page settings;

```bash
https://x.s3.amazonaws.com/my-proj/live/static/cms/js/dist/3.4.1/bundle.forms.pagesmartlinkwidget.min.629da13d8067.jsbundle.admin.widget.min.js
https://x.s3.amazonaws.com/my-proj/live/static/cms/js/dist/3.4.1/bundle.forms.apphookselect.min.eb638e67604e.jsbundle.admin.widget.min.js
```

I've no doubt this will just be an issue affecting me... so any ideas where this might be occurring, and if there is an easy override I can include?

This didn't occur in debug mode.

**Comment by FinalAngel** [comment]
@marksweb thanks for the feedback, @vxsx any feedback?

**Comment by vxsx** [comment]
the issue is the hash in `https://x.s3.amazonaws.com/my-proj/live/static/cms/js/dist/3.4.1/bundle.forms.pagesmartlinkwidget.min.629da13d8067.js`

The `629da13d8067` is unaccounted for when we inject the base admin widget bundle, that's why the path isn't correct.

CMS version in the path should be enough to invalidate the cache, so if you can remove the hash it would start working again.

We can probably adapt our code to work with hashed filenames as well, but that would take some time to happen.

**Comment by marksweb** [comment]
Thanks @vxsx. I've dropped `CachedFilesMixin` from my static storage class so hopefully we won't come across any issues with CMS paths.
