### ISSUE TITLE
django cms error message usage

### ISSUE THREAD

**Issue by jerickbixly** [divio/django-cms#5793]
during testing related to django cms, i came across this error message which pops up from the structure view when i forget to activate runserver

![django_cms_error](https://cloud.githubusercontent.com/assets/2738535/20987978/ad2fb3ca-bd09-11e6-84db-61019fceabdb.png)

i noticed that this particular error message is persistent in both the structure and content view and can only be closed by clicking the "X" on the top right corner. I wish to make use of this particular messaging framework for a django cms plugin but i couldn't find this in the manual. How could i make use of this particular messaging framework for django cms? 

thanks

**Comment by vxsx** [comment]
It can be used like this: https://github.com/divio/django-cms/blob/d49b5449af00c3d5fcff2daad195f2f5edf6920c/cms/static/cms/js/modules/cms.modal.js#L934-L938

We haven't documented public CMS JavaScript API yet, mostly since we did a lot of changes to it recently and didn't want to support deprecations etc, but I think we should do it in the future.

**Comment by jerickbixly** [comment]
thank you very much. I'll try this out.

**Comment by vxsx** [comment]
Sadly I don't think there is.

/cc @czpython

**Comment by jerickbixly** [comment]
okay. thank you very much @vxsx
