### ISSUE TITLE
Plugin Form documentation refers to overriding {% block jquery %} which no longer exists

### ISSUE THREAD

**Issue by trawick** [divio/django-cms#5846]
### Summary

See http://docs.django-cms.org/en/stable/how_to/custom_plugins.html#plugin-form
Search forward for "{% block jquery %}", which no longer exists in cms/templates/admin/cms/page/plugin/change_form.html.

(It was present in cms/templates/admin/cms/page/plugin_change_form.html of Django CMS 2.4.3.)

### Expected behaviour

Explain how to override jQuery version for plugin change forms in current Django CMS, to help those who overrode it in previous versions.  (I don't see anything in 3.0/3.1/3.2/3.3/3.4 release notes.)

#### Actual behaviour

Explains how to override jQuery version in old version of Django CMS

#### Environment

* Python version: N/A
* Django version: N/A
* django CMS version: "stable" version of documentation (2.4.1)

**Comment by vxsx** [comment]
Hi,

It is actually no longer possible to exchange the jquery version anywhere in the cms, since it's bundled together with other code and not exposed (other than CMS.$) anymore.
It wasn't possible since 3.0 as far as i can see from commits

I believe correct action would be to remove that from the docs.
/cc @FinalAngel @evildmp

**Comment by FinalAngel** [comment]
👍

**Comment by evildmp** [comment]
Thanks for the report @trawick, will squash it.

**Comment by trawick** [comment]
Thanks!
