### ISSUE TITLE
Plugins are displayed despite the user has no permission to add them

### ISSUE THREAD

**Issue by bartTC** [divio/django-cms#5871]
### Summary

In structure mode, if the user clicks `+` to add a plugin to a placeholder, all registered plugins are displayed. Even plugins which the user has no (add) permission for. 

Once clicked, the popup/iframe displays that the user has no permission to add this plugin. This is ok so it does not draw a security issue. 

### Expected behaviour

Do not show plugins the user has no permission to add, in the plugin list.

#### Environment

* django CMS version: 3.3.x and 3.4.2

**Comment by haricot** [comment]
I hope that this PR is the right approach #5959

### +Expected behaviour
deactivate the double click for plugins whose user does not have the permissions interface in edit_mode.

If accepted :  
For do this, Do you think you need to modify [cms_tags.CMSEditableObject](https://github.com/divio/django-cms/blob/0d25012fce3743130a4c94418c523faa568f2a76/cms/templatetags/cms_tags.py#L519 ) or modify the [cms/templates/cms/toolbar/plugin.html ](https://github.com/divio/django-cms/blob/0d25012fce3743130a4c94418c523faa568f2a76/cms/templates/cms/toolbar/plugin.html#L3)or js or other? Actually I do not know.

Thanks!

**Comment by FinalAngel** [comment]
@vxsx are there additional adaptions required as mentioned in the PR?

**Comment by vxsx** [comment]
i think overriding the template to not render the "extra" stuff would be ok, unless @czpython disagrees
from the top of my head - there might be problems with building breadcrumbs if one of the plugins in the parent chain isn't available for editing etc but it will definitely need testing

**Comment by czpython** [comment]
Hello @haricot,
Thanks for tackling this.
We would like to limit the scope of the fix to only the plugin selector, deactivating the double click would require a lot of js changes and we're already refactoring parts of that code for 3.5.0.

I'll be checking your PR later today :)

**Comment by haricot** [comment]
Thanks for clarifying it. :)

I see that the tests do not pass, if it has no current user.
I tried to modify the tests, in particular the test_alias and test_plugins to add a user but without success (if that is what must be done?)

Sorry for the unnecessary Travis test, I would have stopped them well if I could.
I will test before locally the next times like ./manage.py test cms.tests.test_alias ;)
