### ISSUE TITLE
Is it possible to save changes before changing from page basic settings to advanced settings in the popup-window?

### ISSUE THREAD

**Issue by carina21** [divio/django-cms#5976]
### Summary

When clicking on page -> page settings, you have on the left bottom corner two buttons to change between basic settings and advanced settings.
If you have edited something on the base settings and change to the advanced settings - the changes won't be saved. Is it possible to trigger a save-command, when switching between basic and advanced settings? 

### Expected behaviour
Trigger a save-command, when switching between basic and advanced settings

#### Actual behaviour
The changes at basic settings will be dismissed at switching to the advanced settings.

#### Environment

* Python version: 2.7
* Django version: 1.9.12
* django CMS version: 3.3.3

**Comment by czpython** [comment]
Hello @carina21  , please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

To answer your question, doing this can cause a lot of confusion as django's admin (other apps) don't autosave, and saving on a GET request is also not good practice.

We could add something that triggers a popup which asks if you really want to leave the current page since you have pending changes. If this sounds good, feel free to create a feature proposal for it on the developers mailing list.
