### ISSUE TITLE
Plugin save on Chrome hides all toolbar buttons

### ISSUE THREAD

**Issue by mailbackwards** [divio/django-cms#6332]
### Summary

I am attempting to upgrade from DjangoCMS 3.4 to 3.5, but encountering an issue with Google Chrome.

After editing and saving a plugin, the toolbar re-renders with none of the buttons except for "More...",  as if the JS suddenly thinks that the screen size is too narrow to display any buttons.

I tested on Firefox and Safari, and ran into no problems with those-- this only seems to happen on Chrome for me. I tried both DjangoCMS 3.5.1 and 3.5.2 with the same results.

### Expected behaviour

When I first load or refresh the page, I see the toolbar as expected:
![image](https://user-images.githubusercontent.com/1697151/38706731-f051b3aa-3e73-11e8-811d-52c293410690.png)

I go to edit a plugin (either by double-clicking or selecting "edit" from the structure view), edit it, and click "Save." I expect it to re-render with the same toolbar display as above.

### Actual behaviour

Instead, after the plugin window closes, the toolbar re-renders with the "More..." button and no others, even though the window is the same width as before:
![image](https://user-images.githubusercontent.com/1697151/38706853-66abc2c0-3e74-11e8-97ea-7126ba117048.png)

### Environment

Chrome: Version 65.0.3325.181 (Official Build) (64-bit)

* Python version: 2.7.14
* Django version: 1.11.11
* django CMS version: 3.5.x

**Comment by vxsx** [comment]
Hi, thanks for the report. So far I couldn't reproduce this error, so it would really help if you could answer these questions:

Are there any errors in the browser console?
Does it reproduce with all site javascript commented out?
Could you provide a minimal project to reproduce?

**Comment by mailbackwards** [comment]
This helped me find the issue-- I isolated the problem to an img tag in the site `<head>`. In this case it's a 1x1 pixel but it's happening with any img, regardless of size or whether it's wrapped inside a `<noscript>`. If I move it to somewhere inside the `<body>` the problem goes away. Does that help reproduce the issue?

**Comment by vxsx** [comment]
I looked a bit into it - this happens because if the browser parser encounters an img tag in the head it assumes that it was fed invalid html and that head at this point is closed and body tag is open. So what happens then is that the image and everything that comes after it in the head is rendered into the body. Now, if there is a `link` tag that load css in the head _after_ that image - it's going to be rendered into the body after the toolbar (because the toolbar is injected into the first position into the body in that same js frame). In Chrome at that point there are no styles because the parser didn't encounter the css file yet. And if there are no styles then the script that calculates the widths of the items in the toolbar thinks they are all equal to window width, which is why you see the "More" button then.

I don't think we need to change anything in the cms for this use case. I would recommend moving the image to the body, where it should be, or at least after the styles.

**Comment by mailbackwards** [comment]
Thank you for your help in finding this. We don't have any css after that image and that head pixel placement is recommended by Facebook in their specs, so we might not be the last to encounter this issue-- but we can work around it on our end without any trouble. Thanks again.
