### ISSUE TITLE
Documentation: polls integration

### ISSUE THREAD

**Issue by geoidesic** [divio/django-cms#6393]
### Summary

http://docs.django-cms.org/en/latest/introduction/plugins.html#the-plugin-model

"In your poll application’s models.py add the following:"

### Expected behaviour
I think some clarification of terminology across all the documentation would be helpful.

My suggested terminology for these 3 entities would be:

* local app  –– maps to a) below
* 3rd party app  –– maps to b) below
* integration app  –– maps to c) below

I would define these on the home page of the documentation, explaining each term, and then I would use them consistently throughout all documentation so that there is never any confusion. 

These are basic DSL principles (https://en.wikipedia.org/wiki/Domain-specific_language) which I really think you should consider adopting within the organisation at large because it prevents a lot of wastage.

### Actual behaviour

It is not clear what is being referred to by "poll application". I can't tell if this means:
a) my own application into which I'm installing polls and creating plugins
b) the djangocms-polls application that I cloned from git
c) the polls_cms_integration application where I'm creating an overridden version of the polls application

My guess from the language used would be b) but this seems wrong because the whole point of creating a polls_cms_integration application is that you don't have to edit the 3rd party polls application.
 

### Environment

* Python version: 3.6.4
* Django version: 1.11.11
* django CMS version: 3.5.1

**Comment by trojjer** [comment]
Agreed, it's unclear as to what app it refers to and where the following `urls.py` is expected to be located:

`@apphook_pool.register  # register the application
class PollsApphook(CMSApp):
    app_name = "polls"
    name = _("Polls Application")

    def get_urls(self, page=None, language=None, **kwargs):
        return ["polls.urls"]`


This tutorial seems unaware of the one before it.

**Comment by trojjer** [comment]
In the Apphooks tutorial t's also unclear as to where the following `urls.py` is expected to be located:

class PollsApphook(CMSApp):
    app_name = "polls"
    name = _("Polls Application")

    def get_urls(self, page=None, language=None, **kwargs):
        return ["polls.urls"]
Apphooks

This tutorial seems unaware of the one before it, or doesn't explain what is meant by polls.urls here. Local app, or third party?

**Comment by evildmp** [comment]
@geoidesic Please refer when possible to the [develop branch of the documentation](http://docs.django-cms.org/en/develop/introduction/04-plugins.html). The latest branch points at the most recent release, so won't incorporate patches made since then.

Regarding the use of 'application', in Django this is a package referred to in (for example) `INSTALLED_APPS` or that you might install using `pip` - but not the project or site in which you'd install packages or plugins.

The `djangocms-polls` application is not cloned, but installed with `pip`, so it won't be available to edit in this project at all (as you note, the point here is not to touch it).

The recent updates to this section should make this less ambiguous in any case.

**Comment by evildmp** [comment]
@trojjer 
```
"polls.urls"

is a way of referring to the `urls` module inside the `polls` application.

Please note also the most recent documentation: http://docs.django-cms.org/en/develop/introduction/05-apphooks.html
