### ISSUE TITLE
3.3.4 tag missing commits from release/3.3.x

### ISSUE THREAD

**Issue by db654** [divio/django-cms#6587]
The menu order fix that resulted from this discussion (https://github.com/divio/django-cms/issues/5752) seems not to have made it into the subsequent tag, 3.3.4.

As you can see from comparing the branch to the tag, there are missing commits.
https://github.com/divio/django-cms/commits/release/3.3.x
https://github.com/divio/django-cms/commits/3.3.4

**Comment by czpython** [comment]
Hello @db654,
Initially the bugfix was planned for 3.3.4 but a security bug was reported and we had to release quickly and without any other changes (to avoid any issues on upgrading).

As a result, this fix was moved to 3.3.5 but because of 3.5 being released, 3.3 support was dropped so I don't think we'll be releasing a 3.3.5 version.

Given that 3.3 was mostly a bugfix release meant to prepare projects for 3.4, I **highly** suggest moving to that version instead.
